export { default as userGenerics } from './user.json' assert { type: "json" };
export { default as appointmentGenerics } from './appointment.json' assert { type: "json" };
export { default as businessGenerics } from './business.json' assert { type: "json" };
export { default as categoryGenerics } from './category.json' assert { type: "json" };
export { default as serviceGenerics } from './services.json' assert { type: "json" };
export { default as dictionaryGenerics } from './dictionary.json' assert { type: "json" };
export { default as adminUserGenerics } from './adminUser.json' assert { type: "json"};
export { default as packageGenerics } from './packageGeneric.json' assert { type: "json"};
export { default as businessBranchGenerics } from './businessBranch.json' assert { type: "json"};
export { default as externalCustomersGenerics } from './externalCustomers.json' assert { type: "json"};
export { default as personGenerics } from './person.json' assert { type: "json"};
export { default as authGenerics } from './auth.json' assert { type: "json"};